"""models

Revision ID: 0386b9b4544b
Revises: 877c898a2cd6
Create Date: 2023-06-17 11:46:47.652717

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = '0386b9b4544b'
down_revision = '877c898a2cd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Instrument',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_table('Person',
    sa.Column('uuid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('Order',
    sa.Column('order_id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('instrument', sa.Integer(), nullable=True),
    sa.Column('user', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('side', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['instrument'], ['Instrument.instrument_id'], name='fk_Order_Instrument_instrument_id_instrument', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['Person.uuid'], name='fk_Order_Person_uuid_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('Subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.Integer(), nullable=True),
    sa.Column('user', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.ForeignKeyConstraint(['instrument'], ['Instrument.instrument_id'], name='fk_Subscription_Instrument_instrument_id_instrument', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['Person.uuid'], name='fk_Subscription_Person_uuid_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Quote',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('bid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('offer', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('instrument', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid'], ['Order.order_id'], name='fk_Quote_Order_order_id_bid', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument'], ['Instrument.instrument_id'], name='fk_Quote_Instrument_instrument_id_instrument', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer'], ['Order.order_id'], name='fk_Quote_Order_order_id_offer', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Quote')
    op.drop_table('Subscription')
    op.drop_table('Order')
    op.drop_table('Person')
    op.drop_table('Instrument')
    # ### end Alembic commands ###
