"""person-createdat

Revision ID: 20d5df0c0f0a
Revises: 524a1d7a38ac
Create Date: 2023-06-17 14:36:43.896823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d5df0c0f0a'
down_revision = '524a1d7a38ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
