"""person-constr4

Revision ID: 3a5453d097d7
Revises: a1ef1e76f26d
Create Date: 2023-06-17 14:53:11.925038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5453d097d7'
down_revision = 'a1ef1e76f26d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
