"""person-createdat

Revision ID: 524a1d7a38ac
Revises: e5f75572d57b
Create Date: 2023-06-17 14:29:15.613817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524a1d7a38ac'
down_revision = 'e5f75572d57b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
