"""instrid_auto_incr

Revision ID: 6f84501a20ae
Revises: ec10ec936a49
Create Date: 2023-06-17 17:21:49.196457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f84501a20ae'
down_revision = 'ec10ec936a49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
