"""instrument_positions

Revision ID: 7904981986a6
Revises: eda4150e5a23
Create Date: 2023-06-19 16:16:12.779642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7904981986a6'
down_revision = 'eda4150e5a23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Instrument', sa.Column('buy_position', sa.DECIMAL(precision=15, scale=4), nullable=True))
    op.add_column('Instrument', sa.Column('sell_position', sa.DECIMAL(precision=15, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Instrument', 'sell_position')
    op.drop_column('Instrument', 'buy_position')
    # ### end Alembic commands ###
