"""person-constr

Revision ID: 7fd5d6ba095a
Revises: 20d5df0c0f0a
Create Date: 2023-06-17 14:41:24.346893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd5d6ba095a'
down_revision = '20d5df0c0f0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
