"""models

Revision ID: 877c898a2cd6
Revises: a5a2460e845f
Create Date: 2023-06-17 11:23:24.117048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877c898a2cd6'
down_revision = 'a5a2460e845f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
