"""person-constr2

Revision ID: 907eb33db5c8
Revises: 7fd5d6ba095a
Create Date: 2023-06-17 14:43:08.360548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907eb33db5c8'
down_revision = '7fd5d6ba095a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
