"""person-constr3

Revision ID: a1ef1e76f26d
Revises: 907eb33db5c8
Create Date: 2023-06-17 14:46:30.986008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ef1e76f26d'
down_revision = '907eb33db5c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
