"""order_time_fields

Revision ID: a8f80a2bdc9d
Revises: b997cb086148
Create Date: 2023-06-18 16:16:35.100284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f80a2bdc9d'
down_revision = 'b997cb086148'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('created_at', sa.BigInteger(), nullable=False))
    op.add_column('Order', sa.Column('updated_at', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Order', 'updated_at')
    op.drop_column('Order', 'created_at')
    # ### end Alembic commands ###
