"""instrid_auto_incr2

Revision ID: afc82f9a78e3
Revises: 6f84501a20ae
Create Date: 2023-06-17 17:22:42.516754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc82f9a78e3'
down_revision = '6f84501a20ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
