"""order-id-constr

Revision ID: b997cb086148
Revises: f7512ff674a1
Create Date: 2023-06-18 11:21:59.144190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b997cb086148'
down_revision = 'f7512ff674a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Order', 'order_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Order', 'user',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Person', 'uuid',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Quote', 'bid',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Quote', 'offer',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Subscription', 'user',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Subscription', 'user',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('Quote', 'offer',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('Quote', 'bid',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('Person', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('Order', 'user',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('Order', 'order_id',
               existing_type=sa.String(length=100),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
