"""person-constr5

Revision ID: d6c937c27c58
Revises: 3a5453d097d7
Create Date: 2023-06-17 15:01:26.305743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c937c27c58'
down_revision = '3a5453d097d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
