"""person-createdat

Revision ID: e5f75572d57b
Revises: 0386b9b4544b
Create Date: 2023-06-17 14:28:03.914270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f75572d57b'
down_revision = '0386b9b4544b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
