"""order fix

Revision ID: f7512ff674a1
Revises: afc82f9a78e3
Create Date: 2023-06-17 19:21:04.584269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7512ff674a1'
down_revision = 'afc82f9a78e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
